schemaVersion: 2.2.0
metadata:
  name: ansible-demo
components:
  - name: tooling-container
    container:
      image: quay.io/ansible/creator-base:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['entrypoint']
      # args: ['tail', '-f', '/dev/null']
commands:
  - id: entrypoint
    exec:
      label: "WORKAROUND to run the entrypoint in Dev Spaces < v3.6"
      component: tooling-container
      commandLine: entrypoint
events:
  postStart:
    - entrypoint
