schemaVersion: 2.2.0
metadata:
  name: ansible-demo
components:
  - name: tooling-container
    container:
      image: quay.io/mloriedo/ansible-creator-ee:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']
commands:
  - id: oc
    exec:
      component: tooling-container
      commandLine: '/usr/local/bin/ansible-playbook /projects/ansible-devspace-demo/playbooks/install_oc.yml'
      workingDir: '/projects/ansible-devspace-demo'
