---
- name: Hello World Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello World I am a new commit!"
    - name: Ensure Httpd is installed
      become: true
      ansible.builtin.systemd:
        name: httpd
        state: started