---
dependency:
  name: galaxy
driver:
  name: delegated
  options: 
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: molecule-ubi8-init-1
    image: registry.access.redhat.com/ubi8/ubi-init
    workingDir: '/tmp'
  - name: molecule-ubi8-init-2
    image: registry.access.redhat.com/ubi8/ubi-init
    workingDir: '/tmp'
  - name: molecule-ubi8-init-3
    image: registry.access.redhat.com/ubi8/ubi-init
    workingDir: '/tmp'
provisioner:
  name: ansible
  # Failing to write the ansible into /.ansible/tmp
  config_options:
    defaults:
      remote_tmp: '/tmp'
    # This just says go back a directory and thats your roles path
    # You can also provide this via pipeline with something like this
    # ANSIBLE_ROLES_PATH: $COLLECTION_ROLES

    # COLLECTIONS_PATH: ${PROJECT_SOURCE}
    # ANSIBLE_ROLES_PATH: ${PROJECT_SOURCE}/${MOLECULE_NAMESPACE}
  inventory:
    group_vars:
      all:
        test_role_file_dest: 'demofile.txt'
        molecule_namespace: ${WORKSPACE_NAMESPACE}
        molecule_pip_dependencies:
          - kubernetes
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  name: default
  test_sequence:
    # - lint
    # - syntax
    # - prepare
    - create
    - converge
    - idempotence
    - verify
