---
dependency:
  name: galaxy
driver:
  name: delegated
  options: 
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: ubi8-int
    image: registry.access.redhat.com/ubi8/ubi-init
provisioner:
  name: ansible
  # env:
    # MOLECULE_NAMESPACE: 'demo'
    # This just says go back a directory and thats your roles path
    # You can also provide this via pipeline with something like this
    # ANSIBLE_ROLES_PATH: $COLLECTION_ROLES

    # COLLECTIONS_PATH: ${PROJECT_SOURCE}
    # ANSIBLE_ROLES_PATH: ${PROJECT_SOURCE}/${MOLECULE_NAMESPACE}
  inventory:
    group_vars:
      all:
        test_role_file_dest: 'demofile.txt'
        molecule_namespace: ${WORKSPACE_NAMESPACE}
        molecule_pip_dependencies:
          - kubernetes
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
