---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  connection: community.okd.oc
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
