name: Build and Push Ansible Creator EE Image

on:
  push:
    branches:
      - 'devspaces-[0-9].[0-9]+-rhel-8'
      - devspaces-3-rhel-8

  workflow_call:
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_PASSWORD:
        required: true

jobs:
  build_ansible_creator_ee_image:
    runs-on: ubuntu-22.04
    if: github.actor != 'che-bot'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.CHE_BOT_GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: "Docker quay.io Login"
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push Docker image; Update image in devfile
        run: |
          echo "Branch name: ${{ github.ref }}"
          branch_name=${{ github.ref }}
          branch_name=${branch_name#refs/heads/}
          if [[ $branch_name == "devspaces-3-rhel-8" ]]; then
            tag="latest"
          else
            tag=$(echo "$branch_name" | grep -o '[0-9]\+\.[0-9]\+')
          fi
          echo "Tag: $tag"
          docker buildx build --platform linux/amd64 --tag quay.io/devspaces/ansible-creator-ee:${tag} --push .
          # rewrite devfile to update digest for ansible-creator-ee
          docker pull quay.io/devspaces/ansible-creator-ee:${tag}
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' quay.io/devspaces/ansible-creator-ee:${tag})
          echo "The image with digest: $digest"
          sed -r -i devfile.yaml -e "s|(image: .+devspaces/ansible-creator-ee.+)|image: ${digest}|g"
      - name: Set up Git
        run: |
          git config --global user.email "che-bot@eclipse.org"
          git config --global user.name "Che bot"
        
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "chore(devfile):update Ansible Creator EE image"
          git push
